name: Brand New Notes

on:
  push:
    branches:
      - main
      - hbs-login-signup
      - ready-login-signup-pages
jobs:
  BNN-Deploy:
    name: BNN-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/${{ secrets.USERNAME }}/frontend/2026_2_BNN && git pull
      - name: Build frontend
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/${{ secrets.USERNAME }}/frontend/2026_2_BNN && npm install --include=dev && npm run build
      - name: Copy frontend
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo cp -rf /home/${{ secrets.USERNAME}}/frontend/2026_2_BNN/public/* /opt/public/
      - name: Synk frontend
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo rsync -av --delete /home/${{ secrets.USERNAME }}/frontend/2026_2_BNN/public/ /opt/public/
