name: Brand New Notes

on:
  push:
    branches:
      - main
      - ready-login-signup-pages
      - notes-page-updating
jobs:
  BNN-Deploy:
    name: BNN-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend code
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          timeout: 10m
          script_stop: true
          script: |
            cd /home/${{ secrets.USERNAME }}/frontend/2026_2_BNN
            git fetch origin
            git checkout -f ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
            npm install --include=dev
            npm run build
            sudo rsync -av --delete /home/${{ secrets.USERNAME }}/frontend/2026_2_BNN/public/ /opt/public/